// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TcSgwGtpuSgwRuleKey struct {
	_       structs.HostLayout
	Teid    uint32
	Ifindex uint32
}

type TcSgwGtpuSgwRuleStats struct {
	_       structs.HostLayout
	Packets uint64
	Bytes   uint64
}

type TcSgwGtpuSgwRuleValue struct {
	_             structs.HostLayout
	Action        uint8
	Pad           [3]uint8
	EgressIfindex uint32
	OuterSrcIp    [4]uint8
	OuterDstIp    [4]uint8
	NewTeid       uint32
	CounterId     uint32
}

// LoadTcSgwGtpu returns the embedded CollectionSpec for TcSgwGtpu.
func LoadTcSgwGtpu() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcSgwGtpuBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcSgwGtpu: %w", err)
	}

	return spec, err
}

// LoadTcSgwGtpuObjects loads TcSgwGtpu and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcSgwGtpuObjects
//	*TcSgwGtpuPrograms
//	*TcSgwGtpuMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcSgwGtpuObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcSgwGtpu()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcSgwGtpuSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcSgwGtpuSpecs struct {
	TcSgwGtpuProgramSpecs
	TcSgwGtpuMapSpecs
	TcSgwGtpuVariableSpecs
}

// TcSgwGtpuProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcSgwGtpuProgramSpecs struct {
	XdpSgwGtpuFunc *ebpf.ProgramSpec `ebpf:"xdp_sgw_gtpu_func"`
}

// TcSgwGtpuMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcSgwGtpuMapSpecs struct {
	SgwFwdMap    *ebpf.MapSpec `ebpf:"sgw_fwd_map"`
	SgwRuleStats *ebpf.MapSpec `ebpf:"sgw_rule_stats"`
}

// TcSgwGtpuVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcSgwGtpuVariableSpecs struct {
}

// TcSgwGtpuObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcSgwGtpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcSgwGtpuObjects struct {
	TcSgwGtpuPrograms
	TcSgwGtpuMaps
	TcSgwGtpuVariables
}

func (o *TcSgwGtpuObjects) Close() error {
	return _TcSgwGtpuClose(
		&o.TcSgwGtpuPrograms,
		&o.TcSgwGtpuMaps,
	)
}

// TcSgwGtpuMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcSgwGtpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcSgwGtpuMaps struct {
	SgwFwdMap    *ebpf.Map `ebpf:"sgw_fwd_map"`
	SgwRuleStats *ebpf.Map `ebpf:"sgw_rule_stats"`
}

func (m *TcSgwGtpuMaps) Close() error {
	return _TcSgwGtpuClose(
		m.SgwFwdMap,
		m.SgwRuleStats,
	)
}

// TcSgwGtpuVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcSgwGtpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcSgwGtpuVariables struct {
}

// TcSgwGtpuPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcSgwGtpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcSgwGtpuPrograms struct {
	XdpSgwGtpuFunc *ebpf.Program `ebpf:"xdp_sgw_gtpu_func"`
}

func (p *TcSgwGtpuPrograms) Close() error {
	return _TcSgwGtpuClose(
		p.XdpSgwGtpuFunc,
	)
}

func _TcSgwGtpuClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcsgwgtpu_bpfel.o
var _TcSgwGtpuBytes []byte
