// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type XdpSgwGtpuSgwRuleKey struct {
	_       structs.HostLayout
	Teid    uint32
	Ifindex uint32
}

type XdpSgwGtpuSgwRuleStats struct {
	_       structs.HostLayout
	Packets uint64
	Bytes   uint64
}

type XdpSgwGtpuSgwRuleValue struct {
	_             structs.HostLayout
	Action        uint8
	Pad           [3]uint8
	EgressIfindex uint32
	OuterSrcIp    [4]uint8
	OuterDstIp    [4]uint8
	NewTeid       uint32
	CounterId     uint32
}

// LoadXdpSgwGtpu returns the embedded CollectionSpec for XdpSgwGtpu.
func LoadXdpSgwGtpu() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpSgwGtpuBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load XdpSgwGtpu: %w", err)
	}

	return spec, err
}

// LoadXdpSgwGtpuObjects loads XdpSgwGtpu and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*XdpSgwGtpuObjects
//	*XdpSgwGtpuPrograms
//	*XdpSgwGtpuMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadXdpSgwGtpuObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadXdpSgwGtpu()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// XdpSgwGtpuSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpSgwGtpuSpecs struct {
	XdpSgwGtpuProgramSpecs
	XdpSgwGtpuMapSpecs
	XdpSgwGtpuVariableSpecs
}

// XdpSgwGtpuProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpSgwGtpuProgramSpecs struct {
	XdpSgwGtpuFunc *ebpf.ProgramSpec `ebpf:"xdp_sgw_gtpu_func"`
}

// XdpSgwGtpuMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpSgwGtpuMapSpecs struct {
	SgwFwdMap    *ebpf.MapSpec `ebpf:"sgw_fwd_map"`
	SgwRuleStats *ebpf.MapSpec `ebpf:"sgw_rule_stats"`
}

// XdpSgwGtpuVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpSgwGtpuVariableSpecs struct {
}

// XdpSgwGtpuObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadXdpSgwGtpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpSgwGtpuObjects struct {
	XdpSgwGtpuPrograms
	XdpSgwGtpuMaps
	XdpSgwGtpuVariables
}

func (o *XdpSgwGtpuObjects) Close() error {
	return _XdpSgwGtpuClose(
		&o.XdpSgwGtpuPrograms,
		&o.XdpSgwGtpuMaps,
	)
}

// XdpSgwGtpuMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadXdpSgwGtpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpSgwGtpuMaps struct {
	SgwFwdMap    *ebpf.Map `ebpf:"sgw_fwd_map"`
	SgwRuleStats *ebpf.Map `ebpf:"sgw_rule_stats"`
}

func (m *XdpSgwGtpuMaps) Close() error {
	return _XdpSgwGtpuClose(
		m.SgwFwdMap,
		m.SgwRuleStats,
	)
}

// XdpSgwGtpuVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadXdpSgwGtpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpSgwGtpuVariables struct {
}

// XdpSgwGtpuPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadXdpSgwGtpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpSgwGtpuPrograms struct {
	XdpSgwGtpuFunc *ebpf.Program `ebpf:"xdp_sgw_gtpu_func"`
}

func (p *XdpSgwGtpuPrograms) Close() error {
	return _XdpSgwGtpuClose(
		p.XdpSgwGtpuFunc,
	)
}

func _XdpSgwGtpuClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpsgwgtpu_bpfel.o
var _XdpSgwGtpuBytes []byte
